name: Reusable Node.js CI Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "20.x"
      working-directory:
        description: "Directory to run the workflow in"
        required: false
        type: string
        default: "."
      run-tests:
        description: "Run tests (true/false)"
        required: false
        type: boolean
        default: true

    secrets:
      NPM_TOKEN:
        description: "NPM token for authentication"
        required: false

jobs:
  node-ci:
    name: Node.js CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      # 🧹 Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧱 Setup Node.js
      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      # 🔐 Configure npm for private packages
      - name: Setup NPM authentication
        if: ${{ secrets.NPM_TOKEN != '' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # 📦 Install dependencies
      - name: Install dependencies
        run: npm ci

      # 🧪 Run tests
      - name: Run tests
        if: ${{ inputs.run-tests == 'true' }}
        run: npm test

      # 🏗️ Build project
      - name: Build project
        run: npm run build --if-present

      # 🐳 Docker build and test
      - name: Build Docker image
        run: |
          docker build -t tayank-node:${{ github.sha }} .

      - name: Test Docker container
        run: |
          docker run --rm tayank-node:${{ github.sha }} node -v

      # 📤 Upload build artifacts (if any)
      - name: Upload build artifacts
        if: ${{ always() && hashFiles('dist/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: node-build-${{ github.sha }}
          path: dist/

      # 🧾 Summary
      - name: Build Summary
        run: |
          echo "✅ Node.js version: $(node -v)"
          echo "📦 NPM version: $(npm -v)"
          echo "🏗️ Build completed for ${{ inputs.working-directory }}"